# Generated by Django 5.1.6 on 2025-04-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_two_factor_auth_active',
            field=models.BooleanField(default=False),
        ),
    ]
