# Generated by Django 5.1.6 on 2025-05-26 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalEnglishWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_words', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EnglishWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField()),
                ('translations', models.JSONField(default='list')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('streak', models.IntegerField(default=0)),
                ('last_check', models.DateTimeField(auto_now_add=True)),
                ('total_invokes', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['added'], name='english_eng_added_f1b019_idx'), models.Index(fields=['-added'], name='english_eng_added_9e95d1_idx'), models.Index(fields=['streak'], name='english_eng_streak_538e88_idx'), models.Index(fields=['last_check'], name='english_eng_last_ch_86c24c_idx')],
            },
        ),
    ]
