# Generated by Django 5.1.6 on 2025-05-27 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='englishwords',
            name='last_check',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='englishwords',
            name='translations',
            field=models.JSONField(default=list),
        ),
    ]
