# Generated by Django 5.1.6 on 2025-06-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0003_alter_englishwords_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='englishwords',
            name='translations',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
