# Generated by Django 5.1.6 on 2025-09-09 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history_dates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historydates',
            name='user',
        ),
    ]
