# Generated by Django 5.1.6 on 2025-09-10 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history_dates', '0002_remove_historydates_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoryDates',
            new_name='HistoryDate',
        ),
    ]
